// <auto-generated />
using System;
using BulletNET.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulletNET.Migrations
{
    [DbContext(typeof(DatabaseDB))]
    partial class DatabaseDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnOrder(0);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<int>("UserID")
                        .HasColumnType("int(11)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.RadarBoard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnOrder(0);

                    b.Property<string>("MainBoardID")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("mainBoardID");

                    b.Property<string>("RadarBoardID")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("radarBoardID");

                    b.HasKey("ID");

                    b.ToTable("MainRadarBoardPairing");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.TestAction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnOrder(0);

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Passed");

                    b.Property<double?>("Maximum")
                        .HasColumnType("double")
                        .HasColumnName("Maximum");

                    b.Property<double?>("Measured")
                        .HasColumnType("double")
                        .HasColumnName("Measured");

                    b.Property<double?>("Minimum")
                        .HasColumnType("double")
                        .HasColumnName("Minimun");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ValueName");

                    b.Property<int>("TestGroupID")
                        .HasColumnType("int(11)");

                    b.HasKey("ID");

                    b.HasIndex("TestGroupID");

                    b.ToTable("TestAction");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.TestGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnOrder(0);

                    b.Property<int?>("CommentID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("RadarBoardID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TimeStamp");

                    b.Property<int>("UserID")
                        .HasColumnType("int(11)");

                    b.HasKey("ID");

                    b.HasIndex("CommentID");

                    b.HasIndex("RadarBoardID");

                    b.HasIndex("TimeStamp")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("TestGroup");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Users.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("USER_DESC");

                    b.Property<string>("Hashcode")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("USER_HASH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USER_NAME")
                        .HasColumnOrder(1);

                    b.Property<int>("RoleNum")
                        .HasColumnType("int")
                        .HasColumnName("USER_ROLE");

                    b.HasKey("ID");

                    b.ToTable("PROG_USER");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.Comment", b =>
                {
                    b.HasOne("BulletNET.EntityFramework.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.TestAction", b =>
                {
                    b.HasOne("BulletNET.EntityFramework.Entities.Radar.TestGroup", "TestGroup")
                        .WithMany("TestActions")
                        .HasForeignKey("TestGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestGroup");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.TestGroup", b =>
                {
                    b.HasOne("BulletNET.EntityFramework.Entities.Radar.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentID");

                    b.HasOne("BulletNET.EntityFramework.Entities.Radar.RadarBoard", "RadarBoard")
                        .WithMany("TestGroups")
                        .HasForeignKey("RadarBoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulletNET.EntityFramework.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("RadarBoard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.RadarBoard", b =>
                {
                    b.Navigation("TestGroups");
                });

            modelBuilder.Entity("BulletNET.EntityFramework.Entities.Radar.TestGroup", b =>
                {
                    b.Navigation("TestActions");
                });
#pragma warning restore 612, 618
        }
    }
}
